/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Information about all the teams leading Catppuccin.
 *
 * @minItems 1
 */
export type AllLeadershipTeams = [LeadershipTeam, ...LeadershipTeam[]];
/**
 * The display name of the team.
 */
export type TeamName = string;
/**
 * A short description of what the team is.
 */
export type Description = string;
/**
 * A list of items that the team is responsible for.
 */
export type Responsibilities = string;
/**
 * The display name of the member.
 */
export type DisplayName = string;
/**
 * The GitHub profile link of the member.
 */
export type GitHubProfile = string;
/**
 * List of all members in this team.
 */
export type CurrentMembers = {
  name: DisplayName;
  url: GitHubProfile;
  [k: string]: unknown;
}[];
/**
 * List of all members who used to be part of the team.
 */
export type PastMembers = {
  name: DisplayName;
  url: GitHubProfile;
  [k: string]: unknown;
}[];

export interface GovernanceSchema {
  leadership: AllLeadershipTeams;
}
export interface LeadershipTeam {
  name: TeamName;
  description: Description;
  responsibilities: Responsibilities;
  "current-members": CurrentMembers;
  "past-members": PastMembers;
  [k: string]: unknown;
}
